#!/bin/ash /etc/rc.common
# shellcheck shell=dash

USE_PROCD=1

config_iface () {
    local iface="$1"
    local macs_file wpa_psk_file ifname
    config_get ifname "$iface" ifname
    config_get macs_file "$iface" macs_file
    config_get wpa_psk_file "$iface" wpa_psk_file \
        "/var/run/hostapd-$ifname.psk"

    if ! [ -r "$macs_file" ]; then
        hostapd_slppsk init "$ifname" "$wpa_psk_file"
    else
        hostapd_slppsk init "$ifname" "$wpa_psk_file" "$macs_file"
    fi
}

config_password () {
    local password="$1"
    local ifname master_pwd temp_entries vlanid ppsk_len wps params
    config_get ifname "$password" ifname
    config_get master_pwd "$password" master_password
    config_get temp_entries "$password" max_temp_entries 20
    config_get vlanid "$password" vlanid 0
    config_get ppsk_len "$password" ppsk_len_bytes 12
    config_get_bool wps "$password" wps 0

    if [ "$wps" != 0 ]; then
        params="wps=1"
    fi
    if [ "$vlanid" != 0 ]; then
        params="$params vlanid=$vlanid"
    fi

    MASTER_PSK="$master_pwd" hostapd_slppsk \
        "$ifname" init-psk \
        "$temp_entries" \
        "$params" \
        "$ppsk_len"
}

start_instance () {
    local iface="$1" ifname pid_file
    config_get ifname "$iface" ifname
    pid_file="$(hostapd_slppsk "$ifname" pid-file)"

    procd_open_instance "$ifname"
    procd_set_param command hostapd_slppsk "$ifname" listen
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param pidfile "$pid_file"
    procd_close_instance
}

start_service () {
    config_load slppsk
    config_foreach config_iface iface
    config_foreach config_password password
    config_foreach start_instance iface
}

stop_instance () {
    local iface="$1"
    config_get ifname "$iface" ifname
    hostapd_slppsk "$ifname" remove
}

stop_service () {
    config_load slppsk
    config_foreach stop_instance iface
}

service_triggers() {
    procd_add_reload_trigger slppsk
}

reload_service() {
    stop
    start
}
